[project]
name = "cfsim"
requires-python = ">=3.12"
version = "0.1.0"
readme = "README.md"
dependencies = [
    "click>=8.0",
    "h5py",
    "pandas",
    "pysam",
    "scipy",
    "statsmodels",
    "matplotlib",
    "seaborn",
    "numpy",
]
scripts = { cfsim = "cfsim.cli:main"}

[build-system]
requires = ["uv_build>=0.11.17,<0.12.0"]
build-backend = "uv_build"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
cfsim = { path = ".", editable = true }

[dependency-groups]
test = ["pytest"]

[tool.pixi.environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }

[tool.pixi.feature.test.pypi-dependencies]
pytest = ">=9.1.1"
pyyaml = ">=6.0.3"

[tool.pytest.ini_options]
pythonpath = ["src", "."]

[tool.pixi.feature.test.tasks]
test_plotting = "pytest tests/test_plotting/test_plot.py"
test_simulate = "pytest tests/test_simulate/test_simulate.py"
test_wig = "pytest tests/test_wig/test_wig.py"
test_cli = "pytest tests/test_cli/"
test_all = { depends_on = ["test_plotting", "test_simulate", "test_wig", "test_cli"] }